spring.application.name=PlayMySongsBackEnd
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=play_my_songs
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
